/*
 * Copyright 2019 ,2021 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v9.0
processor: MK66FN2M0xxx18
package_id: MK66FN2M0VMD18
mcu_data: ksdk2_0
processor_version: 9.0.0
board: FRDM-K66F
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_port.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', prefix: BOARD_, coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: E10, peripheral: UART0, signal: RX, pin_signal: TSI0_CH9/PTB16/SPI1_SOUT/UART0_RX/FTM_CLKIN0/FB_AD17/SDRAM_D17/EWM_IN/TPM_CLKIN0}
  - {pin_num: E9, peripheral: UART0, signal: TX, pin_signal: TSI0_CH10/PTB17/SPI1_SIN/UART0_TX/FTM_CLKIN1/FB_AD16/SDRAM_D16/EWM_OUT_b/TPM_CLKIN1}
  - {pin_num: K6, peripheral: TPIU, signal: SWO, pin_signal: TSI0_CH3/PTA2/UART0_TX/FTM0_CH7/I2C3_SCL/LPUART0_TX/JTAG_TDO/TRACE_SWO/EZP_DO, pull_select: down, pull_enable: disable}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void)
{
    /* Port A Clock Gate Control: Clock enabled */
    //CLOCK_EnableClock(kCLOCK_PortA);
    /* Port B Clock Gate Control: Clock enabled */
    //CLOCK_EnableClock(kCLOCK_PortB);

    CLOCK_EnableClock(kCLOCK_PortC);
    CLOCK_EnableClock(kCLOCK_PortD);
    CLOCK_EnableClock(kCLOCK_PortE);

    PORT_SetPinMux(PORTC, 1U, kPORT_MuxAlt4);

    // UART Pin Mux Setup
    PORT_SetPinMux(PORTC, 12U,kPORT_MuxAlt3);
    PORT_SetPinMux(PORTC, 13U, kPORT_MuxAlt3);
    PORT_SetPinMux(PORTC, 14U, kPORT_MuxAlt3);
    PORT_SetPinMux(PORTC, 15U, kPORT_MuxAlt3);
    PORT_SetPinMux(PORTE, 27U, kPORT_MuxAlt3);

    /*PORT_SetPinMux(PORTB, 8U, kPORT_MuxAsGpio); //kept as 1
        PORT_SetPinMux(PORTB, 10U, kPORT_MuxAlt2);  // accel
        PORT_SetPinMux(PORTB, 17U, kPORT_MuxAlt2); //miso
        PORT_SetPinMux(PORTB, 11U, kPORT_MuxAlt2); //sck
        PORT_SetPinMux(PORTB, 16U, kPORT_MuxAlt2); //mosi
        PORT_SetPinMux(PORTA, 25U, kPORT_MuxAsGpio);*/

    /* PORTB16 (pin E10) is configured as UART0_RX */
   PORT_SetPinMux(PORTB, 16U, kPORT_MuxAlt3);

   /* PORTB17 (pin E9) is configured as UART0_TX */
   PORT_SetPinMux(PORTB, 17U, kPORT_MuxAlt3);

   /* PORTC9 (pin D7) is configured as PTC9 */
   PORT_SetPinMux(PORTC, 9U, kPORT_MuxAlt3);//red led
   PORT_SetPinMux(PORTC, 8U, kPORT_MuxAlt3);//blue led
   PORT_SetPinMux(PORTD, 1U, kPORT_MuxAlt4);// green led


}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
